### ISSUE TITLE
tutorials.deleted and other DB fields have a nonsensical configuration

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#25]
The default is set to null, but null is disallowed. Let's make the default false / 0.

**Comment by simpsonw** [comment]
I took a shot at this.  My changes are in the gh_25_db_fields branch.  I added a default value of 0 for the following columns:

tutorial
-------------
published
deleted
for_credit

users
------------
deleted

Not sure if there are other things that need to be cleaned up, but this seemed like a good start.

**Comment by michaelhagedon** [comment]
I think the defaults were the main nonsense I was referring to. :-)

**Comment by michaelhagedon** [comment]
What I'm seeing looks good. I think it'd be good to go through all the tables and look for 'null' => false, 'default' => null nonsense and do the same. There are more. This has caused some people problems in the past.

**Comment by simpsonw** [comment]
I think these were the main offenders, @michaelhagedon.  I will definitely have another look at the schema.  It appears that the primary and foreign key columns generally have that configuration ("null"=>false, "default"=>null), which makes sense to me since you can't really provide a sensible default for a column like that, so any attempt to write a record that doesn't specify that column should fail.

**Comment by michaelhagedon** [comment]
I think there's some mode MySQL can be in that chokes on configs like that, even if they have no practical effect. Or at least that's my vague recollection of the issue. Gots-discuss archives may remember something more...

**Comment by simpsonw** [comment]
I took a look at [a post in the Google group](https://groups.google.com/forum/#!searchin/gots-discuss/null/gots-discuss/70cpOJhsok8/KNMS5j5MfBYJ) and saw that people were having issues using GotS with MariaDB with strict tables enabled.  I was curious to see if I could reproduce the issue with MySQL, so I changed my my.cnf file to run in strict mode:

```
[mysqld]
#
# * Basic Settings
#
sql_mode=STRICT_ALL_TABLES 
```

When I tried to run the migrations to create the DB, I got an error:
```
There was an error during a migration. 
 The error was: 'SQLSTATE[HY000]: General error: 1364 Field 'deleted' doesn't have a default value' 
 You must resolve the issue manually and try again.
```
This was happening both with master checked out and with my gh_25_db_fields branch checked out.  The problem seems to be that when the database is in strict mode, it chokes on the initial migration (001_initial.php) before it finds the default values that I've added.  Manually editing 001_initial.php to add the default values fixed the issue, but to me it seems kind of odd to edit an existing migration, doubly so when you're adding changes that exist in another migration.

I'm going to have to think about the best way to handle this and am open to suggestions from @michaelhagedon and anybody else about how to best do this.

**Comment by simpsonw** [comment]
For what it's worth, running 
```
../lib/Cake/Console/cake schema update
```
to create the database instead of running
```
../lib/Cake/Console/cake Migrations.migration run all
```
seems to work without issue with strict mode enabled.  Perhaps updating the installation instructions would be the easiest route.

**Comment by michaelhagedon** [comment]
Normally, I would agree that editing migrations is bad. In this case, however, it might be OK. Here’s my reasoning:


·         If someone’s installing from scratch, whether or not the first migration was changed is irrelevant.

·         If someone is upgrading and they already have the sensible field defaults, specifying them again shouldn’t hurt (I think?).

·         If someone is upgrading and they don’t already have the sensible field defaults, they’ll need the later migration to get the sensible defaults.

So maybe having duplication for this is OK?

**Comment by michaelhagedon** [comment]
Not sure about abandoning the migrations plugin, but I’m not clear on the original reasons I chose the migrations plugin over schema. One advantage is that migrations gives a rollback path. Otherwise I don’t know the tradeoffs.

**Comment by simpsonw** [comment]
@michaelhagedon I think you may have a point regarding making an exception in this case.  We shouldn't make a practice of editing the migrations, but it might be the best option in this instance.  I was forgetting that if you run:
```
../lib/Cake/Console/cake schema update
```
Migrations doesn't have any way of figuring out what state your database is at, so if you try to run:
```
../lib/Cake/Console/cake Migrations.migration run up
```
it will start with the first migration.

So yeah, I think in this case I may just manually edit the first migration to have the correct defaults.

**Comment by simpsonw** [comment]
I did a little more investigating on this and figured out that MySQL wasn't choking on the table definition itself, but rather it was choking on the insertion of the default admin user.  We can side step this problem simply by specifying a value for the 'deleted' column when that particular user.

This is, IMO, a lot better and simpler than trying to alter the initial table creation, especially given that in most instances, people will probably want to delete that user after the initial setup of the application anyway.

**Comment by simpsonw** [comment]
I took another look at the schema with the idea that a column should only be nullable with a default value of NULL if and only if it's a required field for the model, which includes keys (both primary keys and foreign keys specified through relationships) and fields who have validation rules that prevent them from being empty.  With that in mind, I identified the following columns that should either have a default value set, be nullable, or have a validation rule to prevent them from being empty:

revisions
---------
content
operation

roles
-----
name

system
------
name

tutorial_types
--------------
name

tutorials
---------
content
dot_creation_timestamp
dot_last_revision_timestamp 
licensing
dot_source_path

I should point out that tutorials.dot_creation_timestamp and tutorials.dot_last_revision_timestamp are actually DATETIME fields rather than TIMESTAMPS, so it's not possible to give them a default value for versions of MySQL before 5.6.5.

I also found that users.password is nullable, which I think is questionable, although I may be missing something here.

Additionally, it appears that there aren't foreign keys being used anywhere, which I find quite alarming.  For example:

```
mysql> show create table resource_types_tutorials;
+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                    | Create Table                                                                                                                                           |
+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| resource_types_tutorials | CREATE TABLE `resource_types_tutorials` (
  `resource_type_id` int(11) NOT NULL,
  `tutorial_id` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 |
+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
I think it's really important that we look into the foreign keys issue, but I believe it would be outside of the scope of this task.  @michaelhagedon what do you think about creating a separate task for that?

**Comment by michaelhagedon** [comment]
@simpsonw Another task is fine with me. Does CakePHP doesn't (or didn't) care about foreign keys at the time...

**Comment by simpsonw** [comment]
Here's a summary of what I've changed:

revisions
------------
content - Now nullable in the database
operation - Now required by the model validation

roles
-------
name - Now required by the model.

tutorials
---------
content - Now nullable (due to external tutorials)
dot_creation_timestamp - Now nullable (only external tutorials seem to use this)
dot_last_revision_timestamp - Now nullable (only external tutorials seem to use this)
licensing - Now nullable (lots of records are just the empty string anyway)
dot_source_path - Now nullable (only external tutorials seem to use this)

users
--------
password - Not not nullable

I wasn't sure what to do with the System model/table.  It doesn't seem to have any records in the last db dump from the live site that I pulled, it has no controller, and no relationships.  Is this actually being used anywhere or should it go?

Additionally, I changed the Revision and Role models to use PHP5 syntax (they were still using the deprecated var keyword).

I believe this is ready for review, @michaelhagedon.

**Comment by michaelhagedon** [comment]
@simpsonw, the System table I think was some idea I had to store, e.g., the GotS version and other relevant metadata. It obviously never went anywhere.

I've reviewed this and it makes sense to me. It seems to follow best practices, even where the code around the changes doesn't necessarily. :-)
