### ISSUE TITLE
Suppress the feedback link

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#73]
Make it possible for a tutorial creator to suppress the feedback link.

**Comment by liquid06** [comment]
We also talked about making the text of the feeback link customizable.

**Comment by simpsonw** [comment]
I have committed some changes to the  gh_73_suppress_feedback_link branch.  I decided to add both the ability to suppress the link and the ability to customize the text.  The general idea works like this:

* When a Tutorial is created, there is a fieldset containing two inputs for the feedback link: a checkbox that controls visibility ("Show feedback link", checked by default) and a text input containing the text for the link ("Feedback link text", set to "What did you think of this tutorial?" by default).
* If the user unchecks "Show feedback link", the text input is disabled.  If they re-check it, it's re-enabled.

I think the basic idea is there, but I'm not 100% sure what to do regarding the link text for existing Tutorials.  I suppose the choices would be to either add a default value to the database column (which feels a bit odd) or have some kind of check in the edit template that would supply a default value (which I think is kind of ugly).

**Comment by simpsonw** [comment]
I've added a configuration option for the feedback link text in config.sample.yml.  If the "Custom Feedback link text" field was left empty, the feedback link text in config.sample.yml will be displayed.  This seemed to make sense to me as a compromise between adding a database default or hard-coding a value in the template.

I believe this task is ready for feedback/review at this point.  I should point out that I haven't committed any changes to the UAL theme repo as I would like to get feedback on the general idea before doing that.

**Comment by liquid06** [comment]
I can't really speak to advantages/disadvantages of the different options for setting he default value...But I tested the branch with the config.yml option and overriding/disabling at the tutorial level worked fine. I have UI/template notes/questions:
* The user clicks a custom link - should that same text be used for the title of the popup form, or would it be annoying if it was long? (As opposed to the un-changeable "Provide Feedback")
* There's add and edit but also *_external. Why include different content on edit as opposed to add? 
* Is there any value of putting the group of fields related to the feedback link into an element to include in all the add/edit files?
* I like the enabled/disabled effect for the custom text field. At first I thought it would be better to hide the field if it's not being used, but since it's enabled by default that doesn't really help with the initial overwhelming impression of the form.
* Should there be an enabled/disabled toggle in the config.yml for whether the feedback link should be turned on at all? That way if someone wanted to turn them off site-wide and they already have a bunch of tutorials, there would be a faster way than editing each tutorial and checking the box.

And a random documentation note: we have changes to config.yml with this upcoming release, but the upgrade instructions tell people to copy in their old config.yml after getting the latest GotS. If they don't have that default option in there for the feedback text, and if they haven't set custom text for each tutorial, the `<a>` element for the feedback link will print with no text in it. So it wouldn't be quite as useful. :confused:

**Comment by simpsonw** [comment]
> The user clicks a custom link - should that same text be used for the title of the popup form, or would it be annoying if it was long? (As opposed to the un-changeable "Provide Feedback")

I like this idea and implemented it in ed48a5a.

> There's add and edit but also *_external. Why include different content on edit as opposed to add? 

I'm not really sure what the initial rationale was for that myself.  Perhaps it might make sense to create a task to look into the possibility of combining the two templates (I've done similar things on other CakePHP projects).

> Is there any value of putting the group of fields related to the feedback link into an element to include in all the add/edit files?

I think there is.  Helps keep things DRY.  I refactored the code to use an element in commit 8c1e530cdd152d2afc089cbb05b42762f3cc8cc3.

> Should there be an enabled/disabled toggle in the config.yml for whether the feedback link should be turned on at all? That way if someone wanted to turn them off site-wide and they already have a bunch of tutorials, there would be a faster way than editing each tutorial and checking the box.

I like this idea as well, but I haven't gotten to implementing it yet.

>And a random documentation note: we have changes to config.yml with this upcoming release, but the upgrade instructions tell people to copy in their old config.yml after getting the latest GotS. If they don't have that default option in there for the feedback text, and if they haven't set custom text for each tutorial, the <a> element for the feedback link will print with no text in it. So it wouldn't be quite as useful. :confused:

I've been a bit worried about the upgrade path for users as well, since there are going to be quite a few changes to config.yml.  It would be cool if there were a script that would help the users upgrade an installation (e.g. copy the appropriate values from an old config.yml to a new one with the new settings in it and run the db updates), but I'm not sure if we'll have time.  Alternatively, we could just update the documentation and advise them to rename their confiig.yml to something like config.yml.bak and then copy config.sample.yml to config.yml and move over the appropriate values.

**Comment by simpsonw** [comment]
I have added the site-wide feedback option in commit 5218860.  I believe this task is ready for another round of feedback and review whenever @liquid06 or @michaelhagedon have time.

**Comment by liquid06** [comment]
Cool! I was wondering if @lsult or @yvonnemery had any suggestions for the UI text on the creator side.

![feedback-link-text](https://cloud.githubusercontent.com/assets/460005/6234528/c430c6aa-b698-11e4-87cc-2c54d7be8fb3.png)

It sounds a little awkward or redundant to me when I read it, but I can't quite figure out why. Maybe since it's already in a fieldset labeled Feedback link, the "Custom feedback link text" could just say "Custom text". Anyway that could just as easily be addressed by making a separate issue to do another iteration on the content for the create/edit form.

Anyway, formal "review" - I only noticed one style detail in your additions to add.js and edit.js. You write `if($(this).attr('checked')){` where other parts of the file are more like `if ($(this).attr('checked')) {` But technically we don't have a js best practice yet, so you can take or leave those spaces I noticed while looking through the commits.

An even tinier detail than that (which isn't part of any UX-Dev best practices but we do tell it content managers): one space after a period. :smiley: (tutorial_feedback_link.ctp line 18)

**Comment by simpsonw** [comment]
@liquid06 I have changed the spacing around the if statements, removed the extra space after the period on line 18 of tutorial_feedback_link.ctp, and changed the label to read "Custom link text" (I am open to any other suggestions, though).  Is there anything else that needs attention?

**Comment by lsult** [comment]
Hey – I like it saying “"Custom text" – thanks for the suggestion Ginger!
Leslie

**Comment by simpsonw** [comment]
The label has been updated to read "Custom text".

**Comment by lsult** [comment]
Thanks!

**Comment by liquid06** [comment]
@simpsonw: I say that this is thoroughly reviewed and ready to be merged. :ok:
