### ISSUE TITLE
Visited link color is confusing

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#92]
Students don't always realized visited links are still clickable.

**Comment by simpsonw** [comment]
I have pushed some changes in the branch gh_92_link_styles.  I have removed the :visted style for the regular tutorial links so that they always appear clickable.  Additionally, I believe there was also concern that the students did not think that the definition box links were clickable, so I have changed the bottom border to be solid rather than dotted to look more like a "regular" link.

**Comment by simpsonw** [comment]
You can see the new styles for the definition links and the regular links at http://webdev.library.arizona.edu/applications/quickHelp/tutorial/1-visited-link-colors-and-definition-boxes-test

**Comment by liquid06** [comment]
Visited links before:
![visited-before](https://cloud.githubusercontent.com/assets/460005/6194296/593e6fd4-b380-11e4-92e5-b457a6ccc5a1.png)
Visited links after:
![visited-after](https://cloud.githubusercontent.com/assets/460005/6194321/87887100-b380-11e4-9a73-cd8cabc1c72c.png)

**Comment by simpsonw** [comment]
Any thoughts on the new look for the links, @lsult and @yvonnemery?

**Comment by lsult** [comment]
Hey I just took a look – one thing that got wonky for me was when I clicked the regular link and then went back, the underline disappeared? I think it would be better for it to stay? Also, is it good or not good practice now to have the color change once you’ve clicked? I actually have no idea, so I’m happy to defer to you guys on that one. I like the definition box link – we found that student didn’t understand to click something that was not blue and underlined, but blue and dots should work?

Thanks for the work on this – I’m super excited for the next release!

**Comment by simpsonw** [comment]
I apologize, @lsult!  I think I may have blown away the changes on the test server before you saw them, which may have caused some strange behavior.  They should be back there now.

Regarding your question about the underline disappearing, this is kind of a quirk with how things are styled right now.  The underline disappears when the link is considered active, so if you were to click elsewhere in the page, it would come back.  Personally, I think it's kind of odd behavior, and I would vote for having the underline only disappear when you hover over a link.

The definition boxes links should look like regular links now, with solid underlines rather than dots.

**Comment by lsult** [comment]
Awesome – ok, I like the solid line and the darker color – I think the solid line makes it clear to click it for the definition box. I’m also with you on having the underline stay.

Thanks!

**Comment by simpsonw** [comment]
@lsult The underline should be staying now (you may have to to reload the page a couple of times to get the new styles).  Regarding changing the color for visited links, we could do that (it's considered standard behavior in fact), but I believe there was concern about students not understanding that visited links were still clickable.  Maybe picking a fairly standard color (like purple) for the visited links would work.

**Comment by yvonnemery** [comment]
Coming in a little late, but just the same feedback that Leslie had about the underline disappearing on the definition box. Another thing, will these be blue?

**Comment by simpsonw** [comment]
@yvonnemery, the underline disappearing should be fixed.  Let me know if it still seems off.

Regarding the colors, the definition box links are currently this shade of blue/gray:

![definition_link_color](https://cloud.githubusercontent.com/assets/10437788/6254919/552ce712-b769-11e4-89f5-aace0ec9bc64.png)

The regular links are this color:

![regular_link_color](https://cloud.githubusercontent.com/assets/10437788/6254926/5d43f62a-b769-11e4-8934-5a08045c9b54.png)

And when you hover over the regular links they turn this color:

![regular_link_hover_color](https://cloud.githubusercontent.com/assets/10437788/6254933/6761c768-b769-11e4-9215-5ba6272cde29.png)

**Comment by simpsonw** [comment]
@lsult has mentioned that #90 is ready for deployment.  What does everyone ( @michaelhagedon, @liquid06, @yvonnemery ) think of the colors for this task?

**Comment by simpsonw** [comment]
Since issue #90 is considered ready for deployment, I am going to merge and deploy this task as well if I don't hear any objections from @yvonnemery or @lsult by the end of the day.  Thanks everyone for your input!

**Comment by simpsonw** [comment]
Looks like the changes for this issue have already been merged into master.  Closing this issue.
